
experiment_settings:
  name: "Test"
  num_runs: 1      # How many times to repeat the experiment with different seeds
  num_episodes: 100 # Number of episodes per run
  results_dir: "results/" # Directory to save plots and data

environment_settings:
  class: "CoinGame"
  params:
    grid_size: 7
    max_steps: 20000
    push_distance: 2

agent_settings:
  player_1:
    class: "DPAgent_PerfectModel" # The class name of the agent from your `agents` module
    params:
      gamma: 0.95
      initial_V_value: 0.0
      termination_criterion: 0.1
      value_iteration_max_num_of_iter: 1000

  player_2:
    class: "ManhattanAgent_Ultra_Aggressive" # The class name of the agent from your `agents` module

plotting_settings:
  moving_average_window: 10