comment: Testing if the result from this run, containing the added reward structure is the same as identical run without it.


experiment_settings:
  name: "LevelK_MDP_DP_Agent_Stationary_vs_LevelK_TMDP_DP_Agent_Stationary"
  num_runs: 1     # How many times to repeat the experiment with different seeds
  num_episodes: 10000 # Number of episodes per run
  run_seed: 42 # Intial seed for runs
  results_dir: "results/" # Directory to save plots and data

environment_settings:
  class: "CoinGame"
  params:
    grid_size: 7
    max_steps: 20000
    push_distance: 2
    rewards:
      # --- General Penalties ---
      step_penalty: -0.1                   # Penalty incurred by each agent on every step.
      out_of_bounds_penalty_delta: -0.5          # Penalty for attempting to move off the grid.
      collision_penalty_delta: -0.05             # Penalty for attempting to move to the same cell as the other player.

      # --- Push-related Rewards/Penalties ---
      push_reward_delta: 0.4                     # Reward for successfully pushing an adjacent opponent.
      push_penalty_delta: -0.2                   # Penalty for being pushed by an opponent.
      push_but_not_adjacent_penalty_delta: -0.05 # Penalty for using the 'push' action when not next to the opponent.
      both_push_penalty_delta: -0.05             # Penalty applied to both players if they push each other simultaneously.

      # --- Coin-related Rewards/Penalties ---
      coin_reward_delta: 2.0                     # Reward for collecting a coin.
      coin_steal_penalty_delta: -0.5             # Penalty for the other player when one player collects a coin.
      contested_coin_penalty_delta: -0.2         # Penalty applied to both players if they try to collect same coin at the same time.

      # --- Terminal (End of Game) Rewards/Penalties ---
      win_reward: 10.0                     # Reward for winning the game (collecting both coins).
      loss_penalty: -10.0                  # Penalty for losing the game.
      draw_penalty: -5.0                   # Penalty for a draw (both coins collected, but neither player won).

      # --- Timeout-related Rewards/Penalties (if max_steps is reached) ---
      timeout_penalty_delta: -2.0                # Base penalty applied to both players if the game times out.
      timeout_lead_bonus_delta: 1.0              # Additional bonus for the player with more coins at timeout.
      timeout_trail_penalty_delta: -1.0          # Additional penalty for the player with fewer coins at timeout.


agent_settings:
  player_1:
    class: LevelK_TMDP_DP_Agent_Stationary
    params:
      gamma: 0.95
      epsilon: 1.0
      initial_V_value: 0
      k: 1
      lower_level_k_epsilon: 0.1

    epsilon_decay_agent:
      type: "linear"           # Options: "linear", "no_decay"
      end: 0.1                 # The final epsilon value.

    # Defines the epsilon decay for the k-1 cognitive hierarchy.
    # This is only used for k-level agents.
    epsilon_decay_inernal_opponent_model:
      type: "linear"           # Options: "linear", "no_decay"
      end: 0.1                 # The final epsilon value.


  player_2:
    class: LevelK_MDP_DP_Agent_Stationary
    params:
      gamma: 0.95
      epsilon: 1.0
      initial_V_value: 0
      k: 1
      lower_level_k_epsilon: 0.1

    epsilon_decay_agent:
      type: "linear"           # Options: "linear", "no_decay"
      end: 0.1                 # The final epsilon value.

    # Defines the epsilon decay for the k-1 cognitive hierarchy.
    # This is only used for k-level agents.
    epsilon_decay_inernal_opponent_model:
      type: "linear"           # Options: "linear", "no_decay"
      end: 0.1                 # The final epsilon value.

plotting_settings:
  moving_average_window: 1000