
experiment_settings:
  name: "Test"
  num_runs: 1     # How many times to repeat the experiment with different seeds
  num_episodes: 10000 # Number of episodes per run
  results_dir: "results/" # Directory to save plots and data

environment_settings:
  class: "CoinGame"
  params:
    grid_size: 7
    max_steps: 20000
    push_distance: 2

agent_settings:
  player_1:
    class: "LevelKQAgent" # The class name of the agent from your `agents` module
    params:
      k: 2
      gamma: 0.95
      learning_rate: 0.5
      epsilon: 1.0
      initial_Q_value: 0.0
      lower_level_k_epsilon: 0.1

    epsilon_decay_agent:
      type: "linear"
      end: 0.1
    epsilon_decay_inernal_opponent_model:
      type: "no_decay"

  player_2:
    class: "LevelKQAgent" # The class name of the agent from your `agents` module
    params:
      k: 1
      gamma: 0.95
      learning_rate: 0.5
      epsilon: 1.0
      initial_Q_value: 0.0
      lower_level_k_epsilon: 0.1

    epsilon_decay_agent:
      type: "linear"
      end: 0.1

plotting_settings:
  moving_average_window: 1000